title: JasonMauss.com
description: Code, Sports, Music, Texas BBQ
footer_text: Copyright 2024 Jason Mauss
header_feature_image: ../uploads/nasahero.jpg
header_text: Code, Sports, Music, and Texas style BBQ
header_text_color: "#e1e1e1"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/1516581774397.jpg
favicon: ../uploads/favicon.ico
gridlayout: false
fixednavbar: true
upzoom: true
items:
  - name: Resume
    siteurl: https://jasonmauss.com/uploads/Jason-Mauss-Resume.pdf
    tab: true
