title: Jason's Blog
description: Code, Sports, Music, Texas BBQ
footer_text: Copyright 2023 Jason Mauss
header_feature_image: ../uploads/nasahero.jpg
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/1516581774397.jpg
favicon: ../uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
